//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Logic.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILogicListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class LogicBaseListener : ILogicListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] LogicParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] LogicParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] LogicParser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] LogicParser.AtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.propositionalWff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropositionalWff([NotNull] LogicParser.PropositionalWffContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.propositionalWff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropositionalWff([NotNull] LogicParser.PropositionalWffContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.propWff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropWff([NotNull] LogicParser.PropWffContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.propWff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropWff([NotNull] LogicParser.PropWffContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.propNegRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropNegRule([NotNull] LogicParser.PropNegRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.propNegRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropNegRule([NotNull] LogicParser.PropNegRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.propAndRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropAndRule([NotNull] LogicParser.PropAndRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.propAndRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropAndRule([NotNull] LogicParser.PropAndRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.propOrRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropOrRule([NotNull] LogicParser.PropOrRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.propOrRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropOrRule([NotNull] LogicParser.PropOrRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.propImpRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropImpRule([NotNull] LogicParser.PropImpRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.propImpRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropImpRule([NotNull] LogicParser.PropImpRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.propBicondRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropBicondRule([NotNull] LogicParser.PropBicondRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.propBicondRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropBicondRule([NotNull] LogicParser.PropBicondRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.propExclusiveOrRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropExclusiveOrRule([NotNull] LogicParser.PropExclusiveOrRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.propExclusiveOrRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropExclusiveOrRule([NotNull] LogicParser.PropExclusiveOrRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] LogicParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] LogicParser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] LogicParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] LogicParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.universal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUniversal([NotNull] LogicParser.UniversalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.universal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUniversal([NotNull] LogicParser.UniversalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.existential"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExistential([NotNull] LogicParser.ExistentialContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.existential"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExistential([NotNull] LogicParser.ExistentialContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicate([NotNull] LogicParser.PredicateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicate([NotNull] LogicParser.PredicateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predicateWff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateWff([NotNull] LogicParser.PredicateWffContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predicateWff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateWff([NotNull] LogicParser.PredicateWffContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predWff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredWff([NotNull] LogicParser.PredWffContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predWff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredWff([NotNull] LogicParser.PredWffContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predQuantifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredQuantifier([NotNull] LogicParser.PredQuantifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predQuantifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredQuantifier([NotNull] LogicParser.PredQuantifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predNegRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredNegRule([NotNull] LogicParser.PredNegRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predNegRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredNegRule([NotNull] LogicParser.PredNegRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predAndRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredAndRule([NotNull] LogicParser.PredAndRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predAndRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredAndRule([NotNull] LogicParser.PredAndRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predOrRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredOrRule([NotNull] LogicParser.PredOrRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predOrRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredOrRule([NotNull] LogicParser.PredOrRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predImpRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredImpRule([NotNull] LogicParser.PredImpRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predImpRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredImpRule([NotNull] LogicParser.PredImpRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predBicondRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredBicondRule([NotNull] LogicParser.PredBicondRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predBicondRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredBicondRule([NotNull] LogicParser.PredBicondRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predExclusiveOrRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredExclusiveOrRule([NotNull] LogicParser.PredExclusiveOrRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predExclusiveOrRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredExclusiveOrRule([NotNull] LogicParser.PredExclusiveOrRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predIdentityRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredIdentityRule([NotNull] LogicParser.PredIdentityRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predIdentityRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredIdentityRule([NotNull] LogicParser.PredIdentityRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predPremise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredPremise([NotNull] LogicParser.PredPremiseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predPremise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredPremise([NotNull] LogicParser.PredPremiseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predConclusion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredConclusion([NotNull] LogicParser.PredConclusionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predConclusion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredConclusion([NotNull] LogicParser.PredConclusionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predProof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredProof([NotNull] LogicParser.PredProofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predProof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredProof([NotNull] LogicParser.PredProofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.propPremise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropPremise([NotNull] LogicParser.PropPremiseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.propPremise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropPremise([NotNull] LogicParser.PropPremiseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.propConclusion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropConclusion([NotNull] LogicParser.PropConclusionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.propConclusion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropConclusion([NotNull] LogicParser.PropConclusionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.propProof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropProof([NotNull] LogicParser.PropProofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.propProof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropProof([NotNull] LogicParser.PropProofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.predSemanticEntailment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredSemanticEntailment([NotNull] LogicParser.PredSemanticEntailmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.predSemanticEntailment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredSemanticEntailment([NotNull] LogicParser.PredSemanticEntailmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogicParser.propSemanticEntailment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropSemanticEntailment([NotNull] LogicParser.PropSemanticEntailmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogicParser.propSemanticEntailment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropSemanticEntailment([NotNull] LogicParser.PropSemanticEntailmentContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
